[package]
name = "jj-sql-lib"
description = "SQL backend for Jujutsu"

version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
balsaq = { path = "../../../balsaq"}
blake2 = { workspace = true }
clru = { workspace = true }
const_format = "0.2.36"
futures = { workspace = true }
itertools = { workspace = true }
jj-lib = { workspace = true }
postcard = { version = "1", features = ["alloc"] }
pollster = { workspace = true }
rusqlite = { version = "0.39.0", features = ["vtab"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
zerocopy = { workspace = true }
zstd = "0.13.3"

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
